Traceback (most recent call last):
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/site-packages/nbclient/client.py", line 609, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/site-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/site-packages/jupyter_client/asynchronous/channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/site-packages/nbclient/client.py", line 816, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/site-packages/nbclient/client.py", line 633, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/Users/br546577/opt/anaconda3/envs/climlab-courseware/lib/python3.7/site-packages/nbclient/client.py", line 684, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 600 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
# Get the water vapor data from CESM output
cesm_data_path = "http://thredds.atmos.albany.edu:8080/thredds/dodsC/CESMA/"
atm_control = xr.open_dataset(cesm_data_path + "cpl_1850_f19/concatenated/cpl_1850_f19.cam.h0.nc")
# Take global, annual average of the specific humidity
weight_factor = atm_control.gw / atm_control.gw.mean(dim='lat')
Qglobal = (atm_control.Q * weight_factor).mean(dim=('lat','lon','time'))
-------------------

